options:
  # Merge default rules (for now)
  merge-default-rules: true

files:
  include: 'src/sass/**/*.s+(a|c)ss'
  ignore:
    - 'src/sass/base/_sprite.scss'
    - 'src/sass/lib/mixins/_grid.sass'

rules:
  no-ids: 0
  force-element-nesting: 0
  property-sort-order: 0
  single-line-per-selector: 0
  no-important: 0
  no-vendor-prefixes: 0
  no-empty-rulesets: 0
  force-pseudo-nesting: 0
  no-qualifying-elements: 0
  no-url-protocols: 0
  no-warn: 0

  nesting-depth:
    - 1
    -
      max-depth: 2

  mixins-before-declarations:
    - 1
    -
      exclude: ['mq']

  leading-zero:
    - 1
    -
      include: true

  no-color-literals:
    - 1
    -
      allow-rgba: true

  no-misspelled-properties:
  - 1
  -
    extra-properties:
      - 'overflow-scrolling'
      - 'flex-preferred-size'
      - 'interpolation-mode'

  quotes:
    - 1
    -
      style: double


  no-duplicate-properties:
    - 1
    -
      exclude:
        - src


  # @TODO update this rules with a appropriate
  # regex to enforce naming style.
  class-name-format: 0
  variable-name-format: 0

  # This is still buggy, see:
  # https://github.com/sasstools/sass-lint/issues/611
  # The compiler will most probably fail
  # anyway if indentation is really wrong.
  indentation: 0

  # Properties that should not be enforced
  # but that can be give some good insight
  # if uncommented temporally.
  no-mergeable-selectors: 0
  placeholder-in-extend: 0
